eval "$(thefuck --alias)"
source ~/kshScripts/prompt.sh
cd
echo "Welcome to the Korn shell!"
echo "Enjoy your stay :3"
eval "$(zoxide init ksh --cmd cd)"
#---Git aliases---#
alias gc="git commit -a"
alias git="hub"
alias gl="git log --oneline --all --graph --decorate"
alias gf="git pull"
alias gp="git push"
alias gco="git checkout"
alias gs="git stash"
alias gd="git diff"
alias gr="git reset --hard HEAD"
#---General aliases---#
alias ls="lsd -A"
alias viksh="vim ~/.kshrc"
alias ce="clear && exec ksh"
alias nerdfetch="nerdfetch -c"
alias cbl="cbonsai -l"
alias shit="fuck -y"
alias whatbroke="sudo systemctl list-units --failed"
alias huh="echo yeah..."
alias mkexec="chmod +x"
alias lookfor="yay -Q | rg"
alias visudo="vim /etc/doas.conf"
alias rr="rm -rf"
alias eshell="emacs -nw --no-splash -f eshell"
alias update="sudo xbps-install -Syu && flatpak update"
alias scug='echo "(\_/)" && echo "|OxO|" && echo "(___)"'
